print('-------------------')
print('\                 /')
print(' \               / ')
print('  \             /  ')
print('   \           /   ')
print('    \         /    ')
print('     \       /     ')
print('      \     /      ')
print('     ---------     ')
print('       /    \      ')
print('      /      \     ')
print('     /        \    ')
print('    /          \   ')
print('   /            \  ')
print('  /              \ ')
print('-------------------')
print('X-GAMA BETA v1.75')